-- Import companies from Collider DB
-- Generated by import_collider_companies.py
-- Date: 2026-01-12

SET search_path TO notalone;

-- SKIPPED (duplicate): Tweed
-- SKIPPED (duplicate): 2Key
-- SKIPPED (duplicate): 22/7
-- SKIPPED (duplicate): Aleph
-- SKIPPED (duplicate): Alsomine
-- SKIPPED (duplicate): Antic
-- SKIPPED (duplicate): Arkhivist
-- SKIPPED (duplicate): B Protocol
-- SKIPPED (duplicate): Backed Finance
-- SKIPPED (duplicate): Bancor
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Beam',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'BEAM is an one layer privacy blockchain scalable confidential cryptocurrency based on Mimblewimble and Lelantus-MW.',
    'https://beam.mw/',
    'Tel Aviv',
    '["Privacy"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Benson Oak Ventures',
    'VC Fund'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Benson Oak Ventures is the Israeli investment arm of the Czech and Slovak investment banking boutique Benson Oaks',
    'https://bensonoakventures.com/',
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Bit2C
-- SKIPPED (duplicate): BitOK
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Bitrated',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Bitrated ensures the credibility of bitcoin and other cryptocurrencies through their identity and reputation management system.',
    'https://www.bitrated.com/',
    'Tel Aviv',
    '["Bitcoin", "Identity"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Bits of Gold',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Online Bitcoin and Ethereum broker in Israel.',
    'https://www.bitsofgold.net/',
    'Tel Aviv',
    '["On/Off Ramp"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Bittax
-- SKIPPED (duplicate): Blockaid
-- SKIPPED (duplicate): BlockBuilders
-- SKIPPED (duplicate): Bloxtax
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Boyo',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'A decentralized IoT startup developing new technologies that link physical rarities with NFT tokens, providing more people with easier access to the Web 3.0',
    'https://boyo.life/',
    'Tel Aviv',
    '["Private Blockchain"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Braavos
-- SKIPPED (duplicate): Breez
-- SKIPPED (duplicate): Certhis
-- SKIPPED (duplicate): Certora
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Chain Reaction',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Developer of blockchain-based hardware product designed to optimize the process of cryptocurrency mining.',
    'https://www.chain-reaction.io/',
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): ChainPort
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Chains',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Chains is developing radically user-friendly, multi-chain cryptocurrency and NFT products.',
    'https://chains.com/',
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Chainstory
-- SKIPPED (duplicate): Chromaway
-- SKIPPED (duplicate): Chromia
-- SKIPPED (duplicate): ClearX
-- SKIPPED (duplicate): Coinmama
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Colu',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Using a unique city currency to help local communities flourish',
    'https://www.colu.com/',
    'Tel Aviv',
    '["Fintech", "Royalty Management"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Cornix
-- SKIPPED (duplicate): Coti
-- SKIPPED (duplicate): Crowdsense
-- SKIPPED (duplicate): Crowdsense
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Crypto Fighters Alliance',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'A play-to-earn (P2E) revamped version of the original CryptoFighters game.',
    'https://www.cryptofighters.io/',
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): CryptoHub
-- SKIPPED (duplicate): Cyberstarts
-- SKIPPED (duplicate): DAOStack
-- SKIPPED (duplicate): DcentraLab
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'DeepDAO',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Data analytics site for decentralized autonomous organizations.',
    'https://deepdao.io/organizations',
    'Tel Aviv',
    '["Data"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'DigitalDogs',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Digital Dogs are driven by powerful artificial intelligence technologies and nurtured by your voice, gestures, emotions, and a digital environment. You can train your Digital Dog to do tricks and perform in competitions, care for them and breed them. AllDigital Dogs are secured as NFTs on the Ethereum blockchain and can be sold, swapped, and shared with other users.',
    'https://digitaldogs.ai/',
    'Tel Aviv',
    '["Metaverse"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Dot Finance
-- SKIPPED (duplicate): dWallet Labs
-- SKIPPED (duplicate): Dynamic
-- SKIPPED (duplicate): Endotech
-- SKIPPED (duplicate): Entree Capital
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'eToro',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Social trading and investment network that allows users to trade currencies, commodities, indices, crypto assets and stocks.',
    'https://www.etoro.com',
    'Tel Aviv',
    '["Fintech", "On/Off Ramp", "Social", "Trading"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Exberry',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Exberry delivers a deep-tech trading infrastructure that offers turnkey solutions for exchanges, banks, digital securities and digital asset marketplaces.',
    'https://exberry.io/',
    'Tel Aviv',
    '["Enterprise", "Fintech"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Fhenix',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'The first L2 powered by fully homomorphic encryption',
    'https://www.fhenix.io/',
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Fireblocks
-- SKIPPED (duplicate): First DAO
-- SKIPPED (duplicate): Flambu
-- SKIPPED (duplicate): Flori Ventures
-- SKIPPED (duplicate): Fuse
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Galaxia Studios',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Galaxia Studios is an innovation hub and web3 gaming studio focused on fully on-chain gaming and dynamic NFTs. Providing true asset ownership, transparency, fairness, and interoperability, creating a more engaging and trust-building gaming experience.',
    NULL,
    'Tel Aviv',
    '["eCommerce", "Payments", "Wallet"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'GK8',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    '[Acquired by Galaxy] GK8 is a cybersecurity company that offers a high-security custodian technology for managing and safeguarding digital assets.',
    'https://gk8.io/',
    'Tel Aviv',
    '["Enterprise", "Hardware"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): GoodDollar
-- SKIPPED (duplicate): Grappa
-- SKIPPED (duplicate): Grateful Giraffes
-- SKIPPED (duplicate): Grix
-- SKIPPED (duplicate): HBH
-- SKIPPED (duplicate): Hexagate
-- SKIPPED (duplicate): Horizen Labs
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Horizon by Altshuler Shaham',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Horizon by Altshuler Shaham operates in the field of digital assets and offers the widest range of coins to trade in the Israeli market.',
    NULL,
    'Tel Aviv',
    '["Cyber Security"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): iAngels
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Ingonyama',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'A semiconductor company, focusing on Zero-Knowledge Proof hardware acceleration, finding and solving computational bottlenecks in ZKPs.',
    'https://www.ingonyama.com/',
    'Tel Aviv',
    '["Zero Knowledge"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'InState',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'InState OS is the ultimate private credit tokenization software platform.',
    NULL,
    'Tel Aviv',
    '["Security Tokens", "Trading"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Jibe
-- SKIPPED (duplicate): Kaspa
-- SKIPPED (duplicate): Kima
-- SKIPPED (duplicate): Kirobo
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'KPMG',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'KPMG’s Blockchain practice helps businesses harness blockchain technology to enhance transparency, efficiency, and security specializing in compliance and forensics. We offer services like blockchain strategy, design partnership, risk management, and system auditing across all industries.',
    'https://kpmg.co.il',
    'Tel Aviv',
    '["Compliance", "Risk Management", "Financial Services", "Strategy", "Economics", "Forensics"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Krayon Digital
-- SKIPPED (duplicate): Lava Network
-- SKIPPED (duplicate): Levana
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'LiquidApps',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'LiquidApps is an open blockchain middleware making Apps scalable, multichain, immortal.',
    'https://liquidapps.io/',
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): LumiShare
-- SKIPPED (duplicate): Magic Square
-- SKIPPED (duplicate): MarketAcross
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Masterkey',
    'VC Fund'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    '-',
    NULL,
    'Tel Aviv',
    '["Marketplace"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Mizmaa Ventures
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'MonkeyLeague',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'A strategy-based web3 sports game. Build a team, compete against real players, climb the Leagues, & earn MonkeyBucks $MBS.',
    'https://www.monkeyleague.io/',
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Moojo.xyz
-- SKIPPED (duplicate): Newhedge
-- SKIPPED (duplicate): Nilos
-- SKIPPED (duplicate): Node Capital
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'nReach',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Find, engage, and track over 1M Web3 contacts to drive engagement and close more deals',
    'https://nreach.io/',
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): nsure.ai
-- SKIPPED (duplicate): Odsy Network
-- SKIPPED (duplicate): Odysseum
-- SKIPPED (duplicate): Ola Finance
-- SKIPPED (duplicate): Oobit
-- SKIPPED (duplicate): Othentic
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Ovio',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'OviO is a mobile games discovery and In-game currency exchange platform for users to buy discounted In-game currencies directly to games.',
    'https://www.ovio.gg/',
    'Tel Aviv',
    '["Marketplace"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Ownera
-- SKIPPED (duplicate): Peerz
-- SKIPPED (duplicate): Pitango
-- SKIPPED (duplicate): Poolz
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Portis',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    '[Acquired by ShapeShift] A platform for making Decentralized Applications accessible to mainstream users.',
    'https://www.portis.io/',
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): PUBLC
-- SKIPPED (duplicate): Rebel Bots
-- SKIPPED (duplicate): Redefine
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Revelator',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Blockchain-enabled technology solutions for record labels, distributors, artist managers, and more.',
    'https://www.revelator.com/',
    'Tel Aviv',
    '["Royalty Management"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Rubber Duck Bath Party',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Rubber Duck Bath Party is a collection of 10,000 hand-drawn, party-loving, dynamic NFTs. Once in a while, your duck will be invited to a bath party - a virtual event where your duck can win, swap, or lose a particular trait. The decision is yours, to party or stay home!',
    'https://duck.art/',
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Samsung Next
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Sayfer',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'SAYFER are experts in targeted audits and penetration tests for the Web3 market, to prevent security breaches in Web3/blockchain projects.',
    'https://sayfer.io/',
    'Tel Aviv',
    '["Cyber Security"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Secret Network
-- SKIPPED (duplicate): SendBlocks
-- SKIPPED (duplicate): ShareMint
-- SKIPPED (duplicate): Simetria
-- SKIPPED (duplicate): Simplex
-- SKIPPED (duplicate): SIRKL
-- SKIPPED (duplicate): SodsBC
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Solidus Labs',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Solidus Labs is a crypto-tracking company that provides tailored compliance and risk monitoring solutions for digital assets.',
    'https://www.soliduslabs.com/',
    'Tel Aviv',
    '["Enterprise", "compliance"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Soundwork
-- SKIPPED (duplicate): SphereX
-- SKIPPED (duplicate): Starkware
-- SKIPPED (duplicate): Taproot Wizards
-- SKIPPED (duplicate): Tectona
-- SKIPPED (duplicate): Tres Finance
-- SKIPPED (duplicate): Tweed
-- SKIPPED (duplicate): Unbound Security
-- SKIPPED (duplicate): Valid Network
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Venn',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Developer of end-to-end cybersecurity platform intended to secure Web3',
    'https://www.venn.build/',
    'Tel Aviv',
    '["Cyber Security"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): Vinsent
-- SKIPPED (duplicate): Viola Ventures
-- SKIPPED (duplicate): Voltage Finance
INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'WelldApp',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'make web3 integration a breeze',
    NULL,
    'Tel Aviv',
    '["Data"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Whitestream',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Provide fraud detection and zero confirmation solution for a much safer & faster transactions on the blockchain',
    'https://www.whitestream.io/',
    'Tel Aviv',
    '["Fraud Prevention"]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

INSERT INTO notalone_companies (
    id, company_name, company_type, sector, status,
    description, website, hq_location, tags, source
) VALUES (
    gen_random_uuid(),
    'Xplorisk',
    'Startup'::company_type,
    'Crypto/Web3',
    'Active'::company_status,
    'Automated and Continuous Web3 Risk Mitigation. Xplorisk is a cutting-edge platform that provides automated risk mitigation and visibility for your Web3/Crypto assets, infrastructure, counterparties, and users. The Xplorisk Ledger, a single view of your entire Web3 environment and user base via our SaaS, API, and Workflow Automation.',
    NULL,
    'Tel Aviv',
    '[]'::jsonb,
    'collider_import_2026'
)
ON CONFLICT (company_name) DO NOTHING;

-- SKIPPED (duplicate): ZenGo
-- Summary: 34 new companies, 101 skipped duplicates